sudo: required

before_install:
  - |
    mkdir -p $HOME/resources
    for i in {0..3}
    do

    if ! [ -f "$HOME/resources/itzpapalotl-v1.2.0.zip" ]; then
      curl -L0 -o $HOME/resources/itzpapalotl-v1.2.0.zip "https://github.com/arangodb-foxx/demo-itzpapalotl/archive/v1.2.0.zip"
    fi

    SHA=$(sha256sum $HOME/resources/itzpapalotl-v1.2.0.zip | cut -f 1 -d " ")
    if [ "${SHA}" = "86117db897efe86cbbd20236abba127a08c2bdabbcd63683567ee5e84115d83a" ]; then
      break
    fi

    $HOME/resources/itzpapalotl-v1.2.0.zip
    done
  - |
    if ! [ -f "$HOME/resources/itzpapalotl-v1.2.0.zip" ]; then
      travis_terminate 1
    fi

services:
  - docker

language: go
go:
  - 1.19.4

env:
  global:
    - GOIMAGE=gcr.io/gcr-for-testing/golang:1.19.4
    - ALPINE_IMAGE=gcr.io/gcr-for-testing/alpine:3.4
    - STARTER=gcr.io/gcr-for-testing/arangodb/arangodb-starter:0.15.7
  jobs:
    - TEST_SUITE=run-unit-tests ALWAYS=1

#    - TEST_SUITE=run-tests-single ARANGODB=eu.gcr.io/arangodb-ci/official/arangodb/arangodb:3.9.6
#    - TEST_SUITE=run-tests-single ARANGODB=gcr.io/gcr-for-testing/arangodb/arangodb:3.10.2 TEST_DISALLOW_UNKNOWN_FIELDS=false ALWAYS=1
#    - TEST_SUITE=run-tests-resilientsingle ARANGODB=gcr.io/gcr-for-testing/arangodb/arangodb:3.10.2
    - TEST_SUITE=run-tests-cluster ARANGODB=gcr.io/gcr-for-testing/arangodb/arangodb:3.10.2
    - TEST_SUITE=run-tests-cluster ARANGODB=gcr.io/gcr-for-testing/arangodb/enterprise:3.10.5
    - TEST_SUITE=run-tests-cluster ARANGODB=gcr.io/gcr-for-testing/arangodb/enterprise-preview:devel-nightly

#    - TEST_SUITE=run-v2-tests-single ARANGODB=eu.gcr.io/arangodb-ci/official/arangodb/arangodb:3.9.6
#    - TEST_SUITE=run-v2-tests-single ARANGODB=gcr.io/gcr-for-testing/arangodb/arangodb:3.10.2 ALWAYS=1
    - TEST_SUITE=run-v2-tests-cluster ARANGODB=gcr.io/gcr-for-testing/arangodb/arangodb:3.10.2
    - TEST_SUITE=run-v2-tests-cluster ARANGODB=gcr.io/gcr-for-testing/arangodb/enterprise:3.10.5
    - TEST_SUITE=run-v2-tests-cluster ARANGODB=gcr.io/gcr-for-testing/arangodb/enterprise-preview:devel-nightly

before_script:
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ ! -z "$ALWAYS" ]; then
      make tools
      make linter
    fi

script:
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ ! -z "$ALWAYS" ]; then
      make $TEST_SUITE TEST_RESOURCES="$HOME/resources/" VERBOSE=1;
    fi
